feat: add option to embeed screenshots
LironEr/cypress-mochawesome-reporter pull request #31
Opened 2021-05-31 18:53 UTC by leonardosimoura

Embedded external screenshots into HTML using base64, combined with inlineAssets option produces a single HTML file
Add new option "embeddedScreenshots" in reporterOptions
for #30

2021-06-04 09:19 UTC, LironEr requested changes

2021-06-04 09:19 UTC, LironEr commented on lib/utils.js
> +    if (contextObj.value) {
The user can also add context, so we need to verify that we don't change user context
`context` can also be a simple string without `title` & `value`.
let's validate `context` is an object & the value starts with `screenshots`

```suggestion
if (typeof context === 'object' && context.value && context.title && context.value.startsWith('screenshots')) {```

2021-06-04 09:19 UTC, LironEr commented on README.md
> +    "embeddedScreenshots": true // embedded external screenshots into HTML using base64, use with inlineAssets option to produces a single HTML file
add 
```
"embeddedScreenshots": true,
"inlineAssets": true
```
to `examples/mochawesome-flags/cypress.json`
so the tests would cover the new feature

2021-06-04 09:19 UTC, LironEr commented on lib/utils.js
> +  function convertContextImgToBase64(contextObj){
I prefer that `convertContextImgToBase64` & `genereatebase64Context` wouldn't be an inner functions of `convertJsonScreenshotsToBase64`, you can move them outside of the function block

2021-06-04 11:49 UTC, lacour-vincent commented
Nice idea to add this option to inline screenshots in base64 !

2021-06-04 12:59 UTC, leonardosimoura commented
Requested changes made

2021-06-05 07:10 UTC, LironEr approved these changes

2021-06-05 07:10 UTC, merged

2021-06-05 07:24 UTC, LironEr commented
Released in [v2.1.0](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v2.1.0)

Thanks @leonardosimoura

2021-06-05 07:24 UTC, LironEr commented
Released in [v2.1.0](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v2.1.0)

Thanks @leonardosimoura